string_indexing = str(input("enter a string:"))
print(" first character:",string_indexing[0])
print(" last character:",string_indexing[-1])
print(" first character:",string_indexing[0:3])
print(" last character:",string_indexing[-1])
print("string reverse :",string_indexing[2])
print(" every second character ",string_indexi[::2])